# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('Photo', models.FileField(upload_to=b'upload')),
                ('Employee_id', models.BigIntegerField()),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
